### ISSUE TITLE
typos in various locations

### ISSUE THREAD

**Issue by Siwel-Yelpoc** [thanhtungdao/ToolsAssignment1#9]
don't know if you have assigned this to yourself or not, but there are some typos in the strings that should be fixed as well.

eg;
CashRegister.java  --  line 19:
   Please enter thee item's cost:
    thee should be thee.
we should check for more issues like this

**Comment by Siwel-Yelpoc** [comment]
I've assigned this to us both, so we just fix them as we find them

**Comment by thanhtungdao** [comment]
Hey,
I mean we can both fix them but the assignment says we assign the issues to different members. So I’ll ask the tutor this afternoon to clarify all my concerns.

Regards,
Thanh Tung Dao
School of ITEE, UniSA

________________________________

**Comment by Siwel-Yelpoc** [comment]
OK, I'll also be at the the practical today.
